name: setup
description: all the setup steps needed for many jobs

inputs:
  shell:
    description: What shell to use
    default: powershell

runs:
  using: "composite"
  steps:
    - shell: ${{ inputs.shell }}
      run: choco install winget --confirm --accept-license --force

    - shell: ${{ inputs.shell }}
      run: .\tools\dev-init.ps1
