name: CI
run-name: ${{ github.actor }} CI
on: [push]

env:
  SHELL: powershell

jobs:
  validate:
    runs-on: windows-latest
    defaults:
      run:
        shell: ${{ env.SHELL }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: "./.github/template/setup"
        with:
          shell: ${{ env.SHELL }}

      - name: InvokeBuild validate
        run: Invoke-Build validate
