name: CI
run-name: ${{ github.actor }} CI
on: [push]
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Powershell Modules
        run: Install-Module InvokeBuild,PSScriptAnalyzer -Scope CurrentUser
